package interfaz;

import AppPackage.AnimationClass;
import algortmos.geometricos.Algoritmos;
import algortmos.geometricos.Punto;
import algortmos.geometricos.pintar;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author diego
 */
public class MainMenu extends javax.swing.JFrame {
    Algoritmos d;
    pintar p = new pintar();
    int c1=0;
    public List <Punto> lista = new ArrayList<>();
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        this.setBounds(0,0,810,425);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        insertaCantidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        algoritmoGraham = new javax.swing.JButton();
        algoritmoQuickhull = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PanelInfo = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(0, 171, 199));
        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 171, 199));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Cantidad de puntos a generar: ");

        insertaCantidad.setBackground(new java.awt.Color(255, 255, 255));
        insertaCantidad.setBorder(null);
        insertaCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertaCantidadActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(0, 171, 199));
        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 171, 199));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Algoritmos");

        algoritmoGraham.setBackground(new java.awt.Color(255, 255, 255));
        algoritmoGraham.setForeground(new java.awt.Color(255, 255, 255));
        algoritmoGraham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/botonGr.png"))); // NOI18N
        algoritmoGraham.setToolTipText("");
        algoritmoGraham.setBorder(null);
        algoritmoGraham.setBorderPainted(false);
        algoritmoGraham.setContentAreaFilled(false);
        algoritmoGraham.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                algoritmoGrahamMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                algoritmoGrahamMouseMoved(evt);
            }
        });
        algoritmoGraham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                algoritmoGrahamMouseExited(evt);
            }
        });
        algoritmoGraham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                algoritmoGrahamActionPerformed(evt);
            }
        });

        algoritmoQuickhull.setBackground(new java.awt.Color(255, 255, 255));
        algoritmoQuickhull.setForeground(new java.awt.Color(255, 255, 255));
        algoritmoQuickhull.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/botonQH.png"))); // NOI18N
        algoritmoQuickhull.setToolTipText("");
        algoritmoQuickhull.setBorder(null);
        algoritmoQuickhull.setBorderPainted(false);
        algoritmoQuickhull.setContentAreaFilled(false);
        algoritmoQuickhull.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                algoritmoQuickhullMouseMoved(evt);
            }
        });
        algoritmoQuickhull.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                algoritmoQuickhullMouseExited(evt);
            }
        });
        algoritmoQuickhull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                algoritmoQuickhullActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(insertaCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jSeparator1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(algoritmoGraham)
                        .addGap(45, 45, 45)
                        .addComponent(algoritmoQuickhull)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(insertaCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(algoritmoQuickhull)
                    .addComponent(algoritmoGraham))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 340, 240));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 171, 199));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 171, 199));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Algortimos Geométricos");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 130));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(0, 171, 199));
        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 171, 199));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Universidad Iberoamericana Puebla");

        jLabel4.setBackground(new java.awt.Color(0, 171, 199));
        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 171, 199));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Prof. Antonio Benítez Ruíz");

        jLabel5.setBackground(new java.awt.Color(0, 171, 199));
        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 171, 199));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Diego Vega De Ita");

        jLabel7.setBackground(new java.awt.Color(0, 171, 199));
        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 171, 199));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Estructura de Datos Y Algoritmos Avanzados");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 280, 130));

        PanelInfo.setBackground(new java.awt.Color(255, 255, 255));
        PanelInfo.setForeground(new java.awt.Color(255, 255, 255));
        PanelInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(0, 171, 199));
        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 171, 199));
        jLabel9.setText("El Algoritmo de Graham calcula la envolvente convexa de un conjunto");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelInfo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 6, -1, -1));

        jLabel10.setBackground(new java.awt.Color(0, 171, 199));
        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 171, 199));
        jLabel10.setText("finito depuntos. Tiene una complejidad de O(n*log n). Fue creado por Ronald");
        PanelInfo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        jLabel11.setBackground(new java.awt.Color(0, 171, 199));
        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 171, 199));
        jLabel11.setText("Graham en 1972. ");
        PanelInfo.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 54, -1, -1));

        jLabel12.setBackground(new java.awt.Color(0, 171, 199));
        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 171, 199));
        jLabel12.setText("El algoritmo calcula todos los vértices de ");
        PanelInfo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 78, -1, -1));

        jLabel13.setBackground(new java.awt.Color(0, 171, 199));
        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 171, 199));
        jLabel13.setText("frontera en la nube de puntos generada.");
        PanelInfo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 126, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Anotación 2020-03-28 152438.png"))); // NOI18N
        jLabel14.setDisabledIcon(null);
        PanelInfo.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 62, -1, -1));

        jLabel15.setBackground(new java.awt.Color(0, 171, 199));
        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 171, 199));
        jLabel15.setText("la envolvente convexa a lo largo de la ");
        PanelInfo.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 102, -1, -1));

        jLabel16.setBackground(new java.awt.Color(0, 171, 199));
        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 171, 199));
        jLabel16.setText("recorriendo desde el punto más bajo");
        PanelInfo.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        jLabel17.setBackground(new java.awt.Color(0, 171, 199));
        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 171, 199));
        jLabel17.setText("hasta crear la envolvente completa");
        PanelInfo.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 174, -1, -1));

        jLabel18.setBackground(new java.awt.Color(0, 171, 199));
        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 171, 199));
        jLabel18.setText("técnica de divide y vencerás");
        PanelInfo.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 174, -1, -1));

        jLabel19.setBackground(new java.awt.Color(0, 171, 199));
        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 171, 199));
        jLabel19.setText("El Algortimo de Quickhull, fue creado por C. Bradford Barber, David");
        PanelInfo.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 6, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Anotación 2020-03-28 152618.png"))); // NOI18N
        PanelInfo.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        jLabel21.setBackground(new java.awt.Color(0, 171, 199));
        jLabel21.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 171, 199));
        jLabel21.setText("P. Dobkin, y Hannu Huhdanpaa en 1996. También crea una envoltura");
        PanelInfo.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        jLabel22.setBackground(new java.awt.Color(0, 171, 199));
        jLabel22.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 171, 199));
        jLabel22.setText("convex en una nube de puntos finitos");
        PanelInfo.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 54, -1, -1));

        jLabel23.setBackground(new java.awt.Color(0, 171, 199));
        jLabel23.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 171, 199));
        jLabel23.setText("Tiene una complejidad de O(n*log r)");
        PanelInfo.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 78, -1, -1));

        jLabel24.setBackground(new java.awt.Color(0, 171, 199));
        jLabel24.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 171, 199));
        jLabel24.setText("con n como numero de puntos y");
        PanelInfo.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 102, -1, -1));

        jLabel25.setBackground(new java.awt.Color(0, 171, 199));
        jLabel25.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 171, 199));
        jLabel25.setText("r como numero de puntos procesados");
        PanelInfo.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 126, -1, -1));

        jLabel26.setBackground(new java.awt.Color(0, 171, 199));
        jLabel26.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 171, 199));
        jLabel26.setText("Este algoritmo está basado en la ");
        PanelInfo.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        getContentPane().add(PanelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 440, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertaCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertaCantidadActionPerformed
        // TODO add your handling code here:
        String c = insertaCantidad.getText();
        c1 = Integer.parseInt(c);
        genera(c1);
        this.d = new Algoritmos(c1);
        d.pega(lista);
        lista.clear();
        p.peg(d.lista);
        p.pegPila(d.pila);
        p.pegPilaPunto(d.pilaPuntos);
        JFrame frame = new JFrame("Nube");
        frame.setSize(1300,700);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        frame.add(p);
    }//GEN-LAST:event_insertaCantidadActionPerformed

    private void algoritmoGrahamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_algoritmoGrahamActionPerformed
        // TODO add your handling code here:
        AnimationClass a = new AnimationClass();
        a.jLabelXLeft(450, 6, 10, 3, jLabel9);
        a.jLabelXLeft(450, 6, 10, 3, jLabel10);
        a.jLabelXLeft(450, 6,10, 3, jLabel11);
        a.jLabelXLeft(450, 6, 10, 3, jLabel12);
        a.jLabelXLeft(450, 6, 10, 3, jLabel13);
        a.jLabelXLeft(450, 256, 10, 1, jLabel14);
        a.jLabelXLeft(450, 6, 10, 3, jLabel15);
        a.jLabelXLeft(450, 6, 10, 3, jLabel16);
        a.jLabelXLeft(450, 6, 10, 3, jLabel17);
        p.lista.clear();
        p.pila.clear();
        p.pilaPuntos.clear();
        if(c1==0){
            JOptionPane.showMessageDialog(null,"No has generado puntos\n");
        }
        else{
            d.Graham();
            p.peg(d.lista);
            p.pegPila(d.pila);
            p.pegPilaPunto(d.pilaPuntos);
            JFrame frame = new JFrame("Nube");
            frame.setSize(1300,700);
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
            frame.add(p);
        }
    }//GEN-LAST:event_algoritmoGrahamActionPerformed

    private void algoritmoQuickhullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_algoritmoQuickhullActionPerformed
        // TODO add your handling code here:
        AnimationClass a = new AnimationClass();
        a.jLabelXLeft(450, 6, 10, 3, jLabel18);
        a.jLabelXLeft(450, 6,10, 3, jLabel19);
        a.jLabelXLeft(450, 230, 10, 1, jLabel20);
        a.jLabelXLeft(450, 6, 10, 3, jLabel21);
        a.jLabelXLeft(450, 6, 10, 3, jLabel22);
        a.jLabelXLeft(450, 6, 10, 3, jLabel23);
        a.jLabelXLeft(450, 6, 10, 3, jLabel24);
        a.jLabelXLeft(450, 6, 10, 3, jLabel25);
        a.jLabelXLeft(450, 6, 10, 3, jLabel26);
        p.lista.clear();
        p.pila.clear();
        p.pilaPuntos.clear();
        if(c1==0){
            JOptionPane.showMessageDialog(null,"No has generado puntos\n");
        }
        else{
            //
            List <Punto> g1 = new ArrayList<>();
            List <Punto> g2 = new ArrayList<>();
            double pos=0;
            int izq=0, dcha=d.lista.size()-1,i;
            d.menorX(izq,dcha);
            d.lista.get(0).setN(0);
            d.lista.get(d.lista.size()-1).setN(d.lista.size()-1);
            System.out.print("Iteraciones de separacion\n");
            i=1;
            while(i<d.lista.size()-1){
                pos=d.determinante(d.lista.get(0),d.lista.get(d.lista.size()-1),d.lista.get(i));
                d.lista.get(i).setN(i);
                System.out.print(d.lista.get(i).n + "\n");
                if(pos<0){
                    g1.add(d.lista.get(i));
                }
                else{
                    g2.add(d.lista.get(i));
                }
                i++;
            }
            System.out.print("En g1 (arriba)\n");
            i=0;
            while(i<g1.size()){
                System.out.print(g1.get(i).x + "\t" + g1.get(i).y + "\t" + g1.get(i).n+ "\n");
                i++;
            }
            System.out.print("En g2 (abajo)\n");
            i=0;
            while(i<g2.size()){
                System.out.print(g2.get(i).x + "\t" + g2.get(i).y + "\t" + g2.get(i).n+ "\n");
                i++;
            }
            //
            d.pilaPuntos.push(d.lista.get(0));
            d.pilaPuntos.push(d.lista.get(d.lista.size()-1));
            d.Quickhull(d.lista.get(0),d.lista.get(d.lista.size()-1),g1);
            d.Quickhull(d.lista.get(d.lista.size()-1),d.lista.get(0),g2);
            p.peg(d.lista);
            p.pegPila(d.pila);
            p.pegPilaPunto(d.pilaPuntos);
            JFrame frame = new JFrame("Nube");
            frame.setSize(1300,700);
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
            frame.add(p);
        }
    }//GEN-LAST:event_algoritmoQuickhullActionPerformed

    private void algoritmoGrahamMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_algoritmoGrahamMouseDragged
        // TODO add your handling code here:
        //algoritmoGraham.setBorder(javax.swing.BorderFactory.createCompoundBorder());
    }//GEN-LAST:event_algoritmoGrahamMouseDragged

    private void algoritmoGrahamMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_algoritmoGrahamMouseMoved
        // TODO add your handling code here:
       algoritmoGraham.setBorder(javax.swing.BorderFactory.createRaisedSoftBevelBorder());
    }//GEN-LAST:event_algoritmoGrahamMouseMoved

    private void algoritmoGrahamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_algoritmoGrahamMouseExited
        // TODO add your handling code here:
        algoritmoGraham.setBorder(javax.swing.BorderFactory.createCompoundBorder());
    }//GEN-LAST:event_algoritmoGrahamMouseExited

    private void algoritmoQuickhullMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_algoritmoQuickhullMouseMoved
        // TODO add your handling code here:
        algoritmoQuickhull.setBorder(javax.swing.BorderFactory.createRaisedSoftBevelBorder());
    }//GEN-LAST:event_algoritmoQuickhullMouseMoved

    private void algoritmoQuickhullMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_algoritmoQuickhullMouseExited
        // TODO add your handling code here:
        algoritmoQuickhull.setBorder(javax.swing.BorderFactory.createCompoundBorder());
    }//GEN-LAST:event_algoritmoQuickhullMouseExited

    //
    public void genera(int t){
        
        int r,s, maxr=1200, minr=0,maxs=600, mins=0;
        int i,j,h=0;
        
        i=0;
        while(i<t){
            r = (int)(Math.random()*(maxr-minr)+minr);
            s = (int)(Math.random()*(maxs-mins)+mins);
            
            if(lista.isEmpty()){
                Punto p = new Punto(r,s);
                lista.add(p);
            }
            else{
                j=0;
                while(j<lista.size()){
                    if(lista.get(j).getX()!=r && lista.get(j).getY()!=s){
                        h=1;
                    }
                    else{
                        h=0;
                        j=lista.size();
                    }
                    j++;
                }
                
                if(h==1){
                    Punto p = new Punto(r,s);
                    lista.add(p);
                }
            }
            i++;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelInfo;
    private javax.swing.JButton algoritmoGraham;
    private javax.swing.JButton algoritmoQuickhull;
    private javax.swing.JTextField insertaCantidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
