/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package byo;

import javax.swing.JOptionPane;
/**
 *
 * @author diego
 */
public class VisualMenuPrincipal extends javax.swing.JFrame {
    //Objeto de tipo arreglo
    Arreglo a;
    //Variables para calcular el tiempo de ejecucion
    long TInicio, TFin, tiempo;
    
    private static VisualMenuPruebas formularioPruebas;
    /**
     * Creates new form Visual
     */
    public VisualMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OrdenaBurbujaBoton = new javax.swing.JButton();
        OrdenaBurbujaBanderaBoton = new javax.swing.JButton();
        BuscaSecuencialBoton = new javax.swing.JButton();
        BuscaSecuencialCentinelaBoton = new javax.swing.JButton();
        BuscaBinariaBoton = new javax.swing.JButton();
        BuscaInterpolacionBoton = new javax.swing.JButton();
        OrdenaSacudidaBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        OrdenaQuicksortBoton = new javax.swing.JButton();
        MenuPruebasBoton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Instancia = new javax.swing.JTextField();
        ValorMin = new javax.swing.JTextField();
        ValorMax = new javax.swing.JTextField();
        salir = new javax.swing.JButton();
        GenerarBoton = new javax.swing.JButton();
        EscribeBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        OrdenaBurbujaBoton.setText("Ordenar por burbuja");
        OrdenaBurbujaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdenaBurbujaBotonActionPerformed(evt);
            }
        });

        OrdenaBurbujaBanderaBoton.setText("Ordenar por burbuja-bandera");
        OrdenaBurbujaBanderaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdenaBurbujaBanderaBotonActionPerformed(evt);
            }
        });

        BuscaSecuencialBoton.setText("Busqueda secuencial");
        BuscaSecuencialBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaSecuencialBotonActionPerformed(evt);
            }
        });

        BuscaSecuencialCentinelaBoton.setText("Busqueda secuencial con centinela");
        BuscaSecuencialCentinelaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaSecuencialCentinelaBotonActionPerformed(evt);
            }
        });

        BuscaBinariaBoton.setText("Busqueda binaria");
        BuscaBinariaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaBinariaBotonActionPerformed(evt);
            }
        });

        BuscaInterpolacionBoton.setText("Busqueda por interpolacion");
        BuscaInterpolacionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaInterpolacionBotonActionPerformed(evt);
            }
        });

        OrdenaSacudidaBoton.setText("Ordenamiento por sacudida");
        OrdenaSacudidaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdenaSacudidaBotonActionPerformed(evt);
            }
        });

        jLabel1.setText("Menú principal");

        OrdenaQuicksortBoton.setText("Ordenamiento por quicksort");
        OrdenaQuicksortBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdenaQuicksortBotonActionPerformed(evt);
            }
        });

        MenuPruebasBoton.setText("Menu de pruebas");
        MenuPruebasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPruebasBotonActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingresa la cantidad de numeros por generar: ");

        jLabel3.setText("Ingresa el valor mínimo del rango: ");

        jLabel4.setText("Ingresa el valor máximo del rango:");

        ValorMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorMinActionPerformed(evt);
            }
        });

        salir.setText("EXIT!!!");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        GenerarBoton.setText("Generar");
        GenerarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarBotonActionPerformed(evt);
            }
        });

        EscribeBoton.setText("Escribir");
        EscribeBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscribeBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Instancia, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(ValorMin)
                                    .addComponent(ValorMax))
                                .addGap(43, 43, 43))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(GenerarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(OrdenaSacudidaBoton)
                                .addGap(18, 18, 18)
                                .addComponent(OrdenaQuicksortBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BuscaSecuencialBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addComponent(BuscaBinariaBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EscribeBoton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(OrdenaBurbujaBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BuscaSecuencialCentinelaBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(OrdenaBurbujaBanderaBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BuscaInterpolacionBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(MenuPruebasBoton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OrdenaBurbujaBoton)
                            .addComponent(OrdenaBurbujaBanderaBoton))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OrdenaSacudidaBoton)
                            .addComponent(OrdenaQuicksortBoton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BuscaSecuencialBoton)
                            .addComponent(BuscaSecuencialCentinelaBoton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BuscaBinariaBoton)
                            .addComponent(BuscaInterpolacionBoton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Instancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ValorMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ValorMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EscribeBoton)
                    .addComponent(salir)
                    .addComponent(GenerarBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(MenuPruebasBoton)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void ValorMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorMinActionPerformed

    private void OrdenaBurbujaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdenaBurbujaBotonActionPerformed
        // TODO add your handling code here:
        TInicio = System.currentTimeMillis();
        a.ordenaBurbuja();
        TFin = System.currentTimeMillis();
        tiempo = TFin - TInicio;
        System.out.print("Tiempo: " + tiempo + "\n");
        JOptionPane.showMessageDialog(null, "Tiempo: " + tiempo);
        
    }//GEN-LAST:event_OrdenaBurbujaBotonActionPerformed

    private void GenerarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarBotonActionPerformed
        // TODO add your handling code here:
        
        String c = Instancia.getText();
        String ma = ValorMax.getText();
        String mi = ValorMin.getText();
        
        int c1 = Integer.parseInt(c);
        int ma1 = Integer.parseInt(ma);
        int mi1 = Integer.parseInt(mi);
        
        this.a = new Arreglo(c1, mi1, ma1);
        a.creaArreglo();
        JOptionPane.showMessageDialog(null, "Instancia: " + c1 + "\n"
                + "Valor mínimo: " + mi1 + "\n" + "Valor Máximo: " + ma1 + "\n");
    }//GEN-LAST:event_GenerarBotonActionPerformed

    private void OrdenaBurbujaBanderaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdenaBurbujaBanderaBotonActionPerformed
        // TODO add your handling code here:
        TInicio = System.currentTimeMillis();
        a.ordenaBurbujaBandera();
        TFin = System.currentTimeMillis();
        tiempo = TFin - TInicio;
        System.out.print("Tiempo: " + tiempo + "\n");
        JOptionPane.showMessageDialog(null, "Tiempo: " + tiempo);
        
    }//GEN-LAST:event_OrdenaBurbujaBanderaBotonActionPerformed

    private void OrdenaSacudidaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdenaSacudidaBotonActionPerformed
        // TODO add your handling code here:
        TInicio = System.currentTimeMillis();
        a.ordenaSacudida();
        TFin = System.currentTimeMillis();
        tiempo = TFin - TInicio;
        System.out.print("Tiempo: " + tiempo + "\n");
        JOptionPane.showMessageDialog(null, "Tiempo: " + tiempo);
    }//GEN-LAST:event_OrdenaSacudidaBotonActionPerformed

    private void OrdenaQuicksortBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdenaQuicksortBotonActionPerformed
        // TODO add your handling code here:
        int derecha=a.m.size()-1;
        int izquierda=0;
        TInicio = System.currentTimeMillis();
        a.ordenaQuicksort(izquierda, derecha);
        TFin = System.currentTimeMillis();
        tiempo = TFin - TInicio;
        System.out.print("Tiempo: " + tiempo + "\n");
        JOptionPane.showMessageDialog(null, "Tiempo: " + tiempo);
    }//GEN-LAST:event_OrdenaQuicksortBotonActionPerformed

    private void BuscaSecuencialBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaSecuencialBotonActionPerformed
        // TODO add your handling code here:
        String firstNumber = JOptionPane.showInputDialog( "Numero a buscar: " );
        
        int number1 = Integer.parseInt( firstNumber );
        int num;
        TInicio = System.nanoTime();
        num = a.busquedaSecuencial(number1);
        TFin = System.nanoTime();
        tiempo = TFin - TInicio;
        
        if(num!=-1){
            JOptionPane.showMessageDialog(null, "Tiempo: " + tiempo + "\n" + "Numero: " + a.m.get(num) + "\n" +"Posicion: " + num + "\n");
        }
        else{
            JOptionPane.showMessageDialog(null, "El número no está en la lista \n"
                    + "Tiempo: " + tiempo);
        }
        
    }//GEN-LAST:event_BuscaSecuencialBotonActionPerformed

    private void BuscaSecuencialCentinelaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaSecuencialCentinelaBotonActionPerformed
        // TODO add your handling code here:
        String firstNumber = JOptionPane.showInputDialog( "Numero a buscar: " );
        
        int number1 = Integer.parseInt( firstNumber );
        int num;
        TInicio = System.nanoTime();
        num = a.busquedaSecuencialCentinela(number1);
        TFin = System.nanoTime();
        tiempo = TFin - TInicio;
        if(num!=-1){
            JOptionPane.showMessageDialog(null, "Tiempo: " + tiempo + "\n" + "Numero: " + a.m.get(num) + "\n" +"Posicion: " + num + "\n");
        }
        else{
            JOptionPane.showMessageDialog(null, "El número no está en la lista \n"
                    + "Tiempo: " + tiempo);
        }
    }//GEN-LAST:event_BuscaSecuencialCentinelaBotonActionPerformed

    private void BuscaBinariaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaBinariaBotonActionPerformed
        // TODO add your handling code here:
        int derecha=a.m.size()-1;
        int izquierda=0;
        a.ordenaQuicksort(izquierda, derecha);
        int num;
        String firstNumber = JOptionPane.showInputDialog( "Numero a buscar: " );
        
        int number1 = Integer.parseInt( firstNumber );
        TInicio = System.nanoTime();
        num = a.busquedaBinaria(number1);
        TFin = System.nanoTime();
        tiempo = TFin - TInicio;
        if(num!=-1){
            JOptionPane.showMessageDialog(null, "Tiempo: " + tiempo + "\n" + "Numero: " + a.m.get(num) + "\n" +"Posicion: " + num + "\n");
        }
        else{
            JOptionPane.showMessageDialog(null, "El número no está en la lista \n"
                    + "Tiempo: " + tiempo);
        }
    }//GEN-LAST:event_BuscaBinariaBotonActionPerformed

    private void BuscaInterpolacionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaInterpolacionBotonActionPerformed
        // TODO add your handling code here:
        int derecha=a.m.size()-1;
        int izquierda=0;
        a.ordenaQuicksort(izquierda, derecha);
        String firstNumber = JOptionPane.showInputDialog( "Numero a buscar: " );
        int number1 = Integer.parseInt( firstNumber );
        int num;
        TInicio = System.nanoTime();
        num = a.busquedaInterpolacion(number1);
        TFin = System.nanoTime();
        tiempo = TFin - TInicio;
        if(num!=-1){
            JOptionPane.showMessageDialog(null, "Tiempo: " + tiempo + "\n" + "Numero: " + a.m.get(num) + "\n" +"Posicion: " + num + "\n");
        }
        else{
            JOptionPane.showMessageDialog(null, "El número no está en la lista \n"
                    + "Tiempo: " + tiempo);
        }
        
    }//GEN-LAST:event_BuscaInterpolacionBotonActionPerformed

    private void EscribeBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscribeBotonActionPerformed
        // TODO add your handling code here:
        a.escribe();
    }//GEN-LAST:event_EscribeBotonActionPerformed

    private void MenuPruebasBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPruebasBotonActionPerformed
        // TODO add your handling code here:
        formularioPruebas = new VisualMenuPruebas();
        formularioPruebas.setVisible(true);
        dispose();
    }//GEN-LAST:event_MenuPruebasBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VisualMenuPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscaBinariaBoton;
    private javax.swing.JButton BuscaInterpolacionBoton;
    private javax.swing.JButton BuscaSecuencialBoton;
    private javax.swing.JButton BuscaSecuencialCentinelaBoton;
    private javax.swing.JButton EscribeBoton;
    private javax.swing.JButton GenerarBoton;
    private javax.swing.JTextField Instancia;
    private javax.swing.JButton MenuPruebasBoton;
    private javax.swing.JButton OrdenaBurbujaBanderaBoton;
    private javax.swing.JButton OrdenaBurbujaBoton;
    private javax.swing.JButton OrdenaQuicksortBoton;
    private javax.swing.JButton OrdenaSacudidaBoton;
    private javax.swing.JTextField ValorMax;
    private javax.swing.JTextField ValorMin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}